name: Test

on: push

jobs:
  unit-test: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22' # The Go version to download (if necessary) and use.
      - run: go version
      - name: unit test
        run: |
          make unit-test
#   integration-test: 
#     needs: [unit-test]
#     runs-on: ubuntu-latest
#     steps:
#       - name: pulling git repo
#         uses: actions/checkout@v4
#       - uses: actions/setup-go@v5
#         with:
#           go-version: '1.22' # The Go version to download (if necessary) and use.
#       - run: go version
#       - name: integration test
#         run: |
#           make integration-test